#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar  1 13:48:59 2024

@author: efuselier

TThis script identifies gene matches between a selected strain
(`ATCC_43300.gb`, `USA100_N315.gb`, `USA300_FPR3757.gb`, `VRSA1.gb`)
and all other listed strains, including Staphylococcus aureus subsp.
aureus NCTC 8325. It produces an output spreadsheet (named
`*_map.xlsx`, where `*` is the GenBank file prefix) in which each row
contains the locus tag, gene name, and product for the reference
strain, along with the corresponding information from each target
strain and the confidence of the match (given by the Levenshtein
similarity ratio).

As written, the script must be run separately for each reference
strain. This is controlled by commenting or uncommenting the code
blocks that define "strain1" (the reference strain) and "strain2" (the
list of comparison strains).

Note: This script depends on files generated by `findmatches_string.py`
and should be run only after that script has been executed.

"""
import genedata_processes as gdp
import pandas as pd
from multiprocessing import Pool
import time
from functools import partial

'''
#gb_file = "ATCC_43300.gb"
#gb_file = "USA100_N315.gb"
#gb_file = "USA300_FPR3757.gb"

gb_file = "VRSA1.gb"
gdp.genbank2excel(gb_file)
stringdata2excel(): 
'''
# Code below requires excel files generated from code above in comments
# for all strains. Alternatively, run findmatces_string.py before this script.

atcc = "ATCC_43300"
usa100 = "USA100_N315"
usa300 = "USA300_FPR3757"
vrsa1 = "VRSA1"

#strain1 = atcc
#strain2 = [usa100,usa300,vrsa1]

#strain1 = usa100
#strain2 = [atcc,usa300,vrsa1]

#strain1 = usa300
#strain2 = [atcc,usa100,vrsa1]

strain1 = vrsa1
strain2 =[atcc,usa100,usa300]

df = pd.read_excel(strain1+'.xlsx')
ids = list(df['locus_tag']);
names = list(df['name']);
seq = list(df['sequence']);

dfout = pd.DataFrame(ids,columns=['locus_tag'])
dfout['NIH_name'] = names
dfout['product'] = list(df['product'])

for strain in strain2:

    dfto = pd.read_excel(strain+'.xlsx')
    targetids = list(dfto['locus_tag']);
    targetnames = list(dfto['name']);
    targetseq = list(dfto['sequence']);
    targetprod = list(dfto['product']);
    
    n = len(seq)
    match = ['']*n
    conf = [-1]*n
    
    t1 = time.time()
    with Pool() as executor:
        X = executor.map(partial(gdp.findmatch,proteinsequences=targetseq),seq)
    
    match = [x[0] for x in X]
    conf = [x[1] for x in X]
    
    t2 = time.time()
    print('total runtime to compute matches:',t2-t1)
    
    # make dictionaries mapping target sequence to target id
    targetseq2id = dict(zip(targetseq,targetids))
    targetseq2name = dict(zip(targetseq,targetnames))
    targetseq2prod = dict(zip(targetseq,targetprod)) 
    
    mappedids = [targetseq2id[x] for x in match]
    mappednames = [targetseq2name[x] for x in match]
    mappedprod = [targetseq2prod[x] for x in match]
    
    dfout[strain+'_match'] = mappedids
    dfout[strain+'_conf'] = conf
    dfout[strain+'_match_name'] = mappednames
    dfout[strain+'_product'] = mappedprod

# Now add the string matches    

strain = 'string'
dfto = pd.read_excel('stringinfo.xlsx')
targetids = list(dfto['#string_protein_id']);
targetnames = list(dfto['preferred_name']);
targetprod = list(dfto['annotation']);

dfto = pd.read_excel('stringsequences.xlsx')
targetseq = list(dfto['sequence']);
 
n = len(seq)
match = ['']*n
conf = [-1]*n

t1 = time.time()
with Pool() as executor:
    X = executor.map(partial(gdp.findmatch,proteinsequences=targetseq),seq)

match = [x[0] for x in X]
conf = [x[1] for x in X]

t2 = time.time()
print('total runtime to compute matches:',t2-t1)

# make dictionaries mapping target sequence to target id
targetseq2id = dict(zip(targetseq,targetids))
targetseq2name = dict(zip(targetseq,targetnames))
targetseq2prod = dict(zip(targetseq,targetprod)) 

mappedids = [targetseq2id[x] for x in match]
mappednames = [targetseq2name[x] for x in match]
mappedprod = [targetseq2prod[x] for x in match]

dfout[strain+'_match'] = mappedids
dfout[strain+'_conf'] = conf
dfout[strain+'_match_name'] = mappednames
dfout[strain+'_product'] = mappedprod

dfout.to_excel(strain1+'_map.xlsx',index=False)